import React from 'react';

const sections = [
  ['1. Introduction', ['La présente politique de confidentialité explique comment Protein Store collecte, utilise, conserve et protège les données personnelles des utilisateurs qui visitent notre site web, créent une commande ou utilisent nos services.', 'Nous accordons une importance particulière à la confidentialité de vos informations personnelles et nous nous engageons à les traiter de manière responsable, conformément à la réglementation applicable en matière de protection des données.']],
  ['2. Collecte des données personnelles', ['Lorsque vous naviguez sur notre site ou passez une commande, nous pouvons collecter les informations d’identification et de contact que vous communiquez (nom, prénom, e-mail et téléphone), les informations nécessaires à la livraison, les données relatives à vos achats et à votre historique de commandes, ainsi que certaines informations techniques de navigation lorsque leur collecte est autorisée.', 'Nous limitons la collecte aux informations nécessaires aux finalités décrites dans cette politique.']],
  ['3. Utilisation des données personnelles', ['Les données peuvent être utilisées pour traiter et suivre vos commandes, organiser la livraison, vous contacter au sujet d’une commande ou d’une réclamation, assurer le fonctionnement et la sécurité du site, améliorer nos services et vous envoyer des offres lorsque cela est autorisé et, si nécessaire, avec votre consentement.', 'Vos données ne sont pas utilisées à des fins incompatibles avec celles pour lesquelles elles ont été collectées.']],
  ['4. Cookies et technologies similaires', ['Le site peut utiliser des cookies ou technologies similaires pour assurer ses fonctionnalités, mémoriser des préférences, faciliter l’utilisation du panier et de la commande, mesurer la fréquentation lorsque ces outils sont utilisés ou personnaliser certains contenus si cette fonctionnalité est activée.', 'Vous pouvez gérer les cookies dans les paramètres de votre navigateur et, lorsqu’un outil de consentement est disponible, depuis les préférences correspondantes. Le refus de cookies non essentiels peut limiter certaines fonctionnalités.']],
  ['5. Partage des données personnelles', ['Certaines données peuvent être communiquées aux prestataires nécessaires au traitement des commandes, à la livraison, au paiement lorsqu’un prestataire est utilisé, à l’hébergement, à la maintenance, à la sécurité du site et au service client.', 'Nous veillons à ce que ces prestataires respectent les obligations applicables de confidentialité et de protection des données. Nous ne vendons pas vos données personnelles à des tiers.']],
  ['6. Sécurité et conservation des données', ['Nous mettons en œuvre des mesures techniques et organisationnelles adaptées pour protéger les données contre la perte, l’altération, la divulgation ou l’accès non autorisé.', 'Les données sont conservées pendant la durée nécessaire aux finalités de leur collecte, sous réserve des obligations légales, comptables ou réglementaires. Leur accès est limité aux personnes et prestataires qui en ont besoin.']],
  ['7. Vos droits concernant vos données personnelles', ['Selon les conditions prévues par la réglementation applicable, vous pouvez demander l’accès à vos données, leur rectification ou leur suppression lorsque cela est juridiquement possible, vous opposer à certains traitements, demander leur limitation, retirer votre consentement ou exercer les autres droits prévus par la loi.', 'Certaines données peuvent devoir être conservées pour respecter des obligations légales ou défendre des droits en justice. Pour exercer vos droits, contactez-nous à contact@proteinstore.tn.']],
  ['8. Protection des mineurs', ['Notre site n’est pas destiné à collecter sciemment des données personnelles auprès de mineurs sans respecter les exigences légales applicables. Si vous estimez que des données ont été collectées de manière inappropriée, contactez-nous afin que nous puissions examiner la situation.']],
  ['9. Modifications de la politique de confidentialité', ['Nous pouvons modifier cette politique pour tenir compte de l’évolution de nos services, de nos pratiques ou de la réglementation. Toute modification sera publiée sur cette page avec une mise à jour de la date de révision.']],
  ['10. Contact', ['Pour toute question concernant cette politique ou le traitement de vos données, contactez Protein Store à contact@proteinstore.tn. Nous nous efforcerons de répondre dans les délais prévus par la réglementation applicable.']],
];

export const PrivacyPolicyPage = () => <article className="mx-auto w-full max-w-4xl px-4 py-16 sm:px-6">
  <header className="mb-10 border-b border-white/10 pb-6"><p className="text-xs font-black uppercase tracking-[.25em] text-[#d90429]">Protein Store Tunisia</p><h1 className="mt-3 text-3xl font-black text-white">Politique de confidentialité</h1><p className="mt-3 text-sm text-gray-500">Dernière mise à jour : 10 octobre 2026</p></header>
  <div className="space-y-8 text-sm leading-7 text-gray-300">{sections.map(([title, paragraphs]) => <section key={title}><h2 className="mb-2 text-lg font-bold text-white">{title}</h2>{paragraphs.map((paragraph) => <p className="mb-2" key={paragraph}>{paragraph}</p>)}</section>)}</div>
</article>;
export default PrivacyPolicyPage;
