import React from 'react';

const sections = [
  ['1. Objet et champ d’application', 'Ces conditions définissent les règles applicables à l’accès au site Protein Store, à la consultation du catalogue et à l’achat des produits. En naviguant ou en commandant, l’utilisateur reconnaît en avoir pris connaissance.'],
  ['2. Présentation des produits', 'Nous nous efforçons de présenter les produits avec des informations précises. Les photographies sont illustratives et de légères différences d’apparence ou d’emballage peuvent exister. Consultez les informations figurant sur l’emballage et les notices du fabricant avant utilisation.'],
  ['3. Prix et disponibilité', 'Les prix sont indiqués dans la devise affichée au moment de la commande. Les frais applicables sont communiqués avant validation. Les produits sont proposés dans la limite des stocks disponibles. Le prix applicable est celui affiché lors de la validation, sous réserve d’une erreur manifeste ou d’une disposition légale contraire.'],
  ['4. Commandes', 'Sélectionnez les produits et ajoutez-les au panier. Avant de confirmer, vérifiez les produits, quantités, coordonnées, adresse de livraison et montant total. Protein Store peut vous contacter pour vérifier les informations nécessaires au traitement de la commande.'],
  ['5. Paiement', 'Les moyens de paiement disponibles sont ceux proposés sur le site au moment de la commande. Les opérations réalisées par un prestataire externe peuvent également être soumises à ses conditions.'],
  ['6. Livraison', 'Les commandes sont livrées aux adresses et dans les zones desservies indiquées sur le site. Les délais communiqués sont estimatifs sauf indication contraire et peuvent varier. Le client est responsable de l’exactitude de son adresse. En cas de colis visiblement endommagé, prenez des photos et contactez rapidement le service client.'],
  ['7. Modification et annulation', 'Toute demande doit être adressée au service client dans les meilleurs délais. La possibilité de modifier ou d’annuler une commande dépend de son état de traitement et d’expédition, sans préjudice des droits prévus par la réglementation.'],
  ['8. Retours, échanges et remboursements', 'Les demandes sont examinées conformément à la politique de retour de Protein Store et à la réglementation applicable. Des conditions particulières peuvent concerner les produits ouverts, descellés ou endommagés. Contactez le service client avant tout retour.'],
  ['9. Packs personnalisés et promotions', 'La composition, le prix et la disponibilité d’un pack dépendent des produits sélectionnés, des tarifs et des stocks. Vérifiez le prix affiché par le configurateur avant validation. Les offres et codes promo sont soumis aux conditions indiquées lors de leur publication.'],
  ['10. Utilisation des compléments alimentaires', 'Les produits complètent l’alimentation et ne sont pas des médicaments. Les informations du site ne remplacent pas l’avis d’un professionnel de santé. Respectez les instructions, doses et précautions figurant sur l’emballage. En cas de grossesse, d’allaitement, de traitement, de pathologie ou de doute, consultez un professionnel de santé. Aucun résultat sportif particulier n’est garanti.'],
  ['11. Responsabilité de l’utilisateur', 'L’utilisateur s’engage à fournir des informations exactes et à utiliser le site conformément aux lois applicables. Toute utilisation abusive, tentative de fraude ou action compromettant la sécurité du site est interdite.'],
  ['12. Propriété intellectuelle', 'Les textes, photographies, logos, visuels et autres éléments du site sont protégés par les droits de propriété intellectuelle applicables. Leur utilisation sans autorisation est interdite sauf disposition légale contraire.'],
  ['13. Données personnelles', 'Les données personnelles sont traitées conformément à notre Politique de confidentialité, qui précise les données collectées, leurs finalités, leur partage et les droits des utilisateurs.'],
  ['14. Disponibilité et sécurité du site', 'Nous faisons des efforts raisonnables pour assurer le fonctionnement et la disponibilité du site. Des interruptions temporaires peuvent survenir pour maintenance, mises à jour, problèmes techniques ou circonstances indépendantes de notre volonté.'],
  ['15. Modification des conditions', 'Protein Store peut mettre à jour ces conditions pour tenir compte de l’évolution de ses services ou de la réglementation. La version en vigueur est celle publiée sur le site au moment de la consultation ou de la commande, sous réserve des règles applicables.'],
  ['16. Droit applicable et litiges', 'Ces conditions sont soumises au droit applicable à l’activité de Protein Store, sous réserve des dispositions impératives de protection des consommateurs. En cas de difficulté, contactez notre service client pour rechercher une solution amiable.'],
  ['17. Contact', 'Pour toute question concernant ces conditions, une commande, une livraison ou un produit, contactez Protein Store à contact@proteinstore.tn.'],
];

export const TermsPage = () => <article className="mx-auto w-full max-w-4xl px-4 py-16 sm:px-6">
  <header className="mb-10 border-b border-white/10 pb-6"><p className="text-xs font-black uppercase tracking-[.25em] text-[#d90429]">Protein Store Tunisia</p><h1 className="mt-3 text-3xl font-black text-white">Conditions générales d’utilisation et de vente</h1><p className="mt-3 text-sm text-gray-500">Dernière mise à jour : 10 octobre 2026</p></header>
  <div className="space-y-8 text-sm leading-7 text-gray-300">{sections.map(([title, text]) => <section key={title}><h2 className="mb-2 text-lg font-bold text-white">{title}</h2><p>{text}</p></section>)}</div>
</article>;
export default TermsPage;
